### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by AndreaPi** [martinzlocha/anchor-optimization#6]
```
python optimize_anchors.py annotations.csv --no-resize --include-stride --seed=1
```
fails with error:

```
Traceback (most recent call last):
  File "optimize_anchors.py", line 10, in <module>
    from compute_overlap import compute_overlap
  File "__init__.pxd", line 872, in init compute_overlap
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

What's happening? My environment: a Docker container with

```
Ubuntu 18.04.3 LTS
Python 3.6.8
```

`pip -list `output:

```
Package                Version  
---------------------- ---------
absl-py                0.8.0    
anchor-optimization    0.0.1    
astor                  0.8.0    
attrs                  19.1.0   
audioread              2.1.8    
backcall               0.1.0    
bleach                 3.1.0    
cloudpickle            1.2.2    
cupy                   6.3.0    
cycler                 0.10.0   
Cython                 0.29.13  
decorator              4.4.0    
defusedxml             0.6.0    
entrypoints            0.3      
fastrlock              0.4      
future                 0.17.1   
gast                   0.2.2    
google-pasta           0.1.7    
graphsurgeon           0.4.1    
grpcio                 1.23.0   
h5py                   2.9.0    
horovod                0.18.0   
ipykernel              5.1.2    
ipython                7.8.0    
ipython-genutils       0.2.0    
jedi                   0.15.1   
Jinja2                 2.10.1   
joblib                 0.13.2   
json5                  0.8.5    
jsonschema             3.0.2    
jupyter-client         5.3.1    
jupyter-core           4.5.0    
jupyter-tensorboard    0.1.10   
jupyterlab             1.0.2    
jupyterlab-server      1.0.0    
jupytext               1.2.3    
Keras                  2.3.1    
Keras-Applications     1.0.6    
Keras-Preprocessing    1.0.5    
keras-resnet           0.1.0    
keras-retinanet        0.5.1    
kiwisolver             1.1.0    
librosa                0.6.3    
llvmlite               0.29.0   
Markdown               3.1.1    
MarkupSafe             1.1.1    
matplotlib             3.1.1    
mistune                0.8.4    
mock                   3.0.5    
mpi4py                 3.0.2    
nbconvert              5.6.0    
nbformat               4.4.0    
nltk                   3.2.5    
notebook               5.7.8    
numba                  0.44.1   
numpy                  1.14.5   
nvidia-dali            0.13.0   
nvidia-dali-tf-plugin  0.13.0   
opencv-python          4.1.1.26 
pandas                 0.23.0   
pandocfilters          1.4.2    
parso                  0.5.1    
pexpect                4.7.0    
pickleshare            0.7.5    
Pillow                 5.4.1    
pip                    19.2.3   
portpicker             1.3.1    
progressbar2           3.47.0   
prometheus-client      0.7.1    
prompt-toolkit         2.0.9    
protobuf               3.9.1    
psutil                 5.6.3    
ptyprocess             0.6.0    
pycocotools            2.0.0    
Pygments               2.4.2    
pyparsing              2.4.2    
pyrsistent             0.15.4   
python-dateutil        2.8.0    
python-speech-features 0.6      
python-utils           2.3.0    
pytz                   2019.2   
PyYAML                 5.1.2    
pyzmq                  18.1.0   
resampy                0.2.1    
sacrebleu              1.3.6    
scikit-learn           0.21.3   
scipy                  1.3.1    
Send2Trash             1.5.0    
sentencepiece          0.1.82   
setuptools             41.2.0   
six                    1.12.0   
tensorboard            1.14.0+nv
tensorflow-estimator   1.14.0   
tensorflow-gpu         1.14.0+nv
tensorrt               6.0.1.4  
termcolor              1.1.0    
terminado              0.8.2    
testpath               0.4.2    
tornado                6.0.3    
tqdm                   4.36.0   
traitlets              4.3.2    
typing                 3.7.4.1  
uff                    0.6.5    
wcwidth                0.1.7    
webencodings           0.5.1    
Werkzeug               0.15.6   
wheel                  0.33.6   
wrapt                  1.11.2 
```

**Comment by AndreaPi** [comment]
This is weird, I can't seem to reproduce the issue on the latest commit https://github.com/martinzlocha/anchor-optimization/commit/05d9b248e94b317f07e957b45b246ffa05514368 , even though the changes have nothing to do with Numpy. Anyway, it works now, so I'm closing this.

**Comment by AndreaPi** [comment]
This is weird, I can't seem to reproduce the issue on the latest commit https://github.com/martinzlocha/anchor-optimization/commit/05d9b248e94b317f07e957b45b246ffa05514368 , even though the changes have nothing to do with Numpy. Anyway, it works now, so I'm closing this.
